// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/anhro/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from appAInjector.go:

func BuildAInCompileTimeWithWire() (A, error) {
	d := NewD()
	c, err := NewC(d)
	if err != nil {
		return nil, err
	}
	b := NewB(c)
	a := NewA(b, c)
	return a, nil
}

// Injectors from appBInjector.go:

func BuildBInCompileTimeWithWire() (B, error) {
	d := NewD()
	c, err := NewC(d)
	if err != nil {
		return nil, err
	}
	b := NewB(c)
	return b, nil
}

// Injectors from appCInjector.go:

func BuildCInCompileTimeWithWire() (C, error) {
	d := NewD()
	c, err := NewC(d)
	if err != nil {
		return nil, err
	}
	return c, nil
}

// Injectors from appWireInjector.go:

func BuildAppInCompileTimeWithWire() (*App, error) {
	d := NewD()
	c, err := NewC(d)
	if err != nil {
		return nil, err
	}
	b := NewB(c)
	a := NewA(b, c)
	app := NewApp(a)
	return app, nil
}
