// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/anhro/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"fmt"
)

// Injectors from wire.go:

func injectedBaz() Baz {
	mainFoo := provideAlternateFoo()
	mainBar := provideBar(mainFoo)
	mainBaz := provideBaz(mainBar)
	return mainBaz
}

func injectedBar() Bar {
	mainFoo := provideFoo()
	mainBar := provideBar(mainFoo)
	return mainBar
}

// wire.go:

func main() {
	fmt.Println(injectedBaz().GetName())
}
